server:
  port: 80
  baseURL: "/"
  database: /home/filebrowser/db/database.db
  sources:
    - path: /host
      config:
        defaultEnabled: true
        defaultUserScope: "/"
    - path: /host-rw/srv-viewport
      config:
        defaultEnabled: true
        defaultUserScope: "/"
auth:
  methods:
    password:
      enabled: true
frontend:
  name: "Viewport VPS"
